docs_dir: 'docs'
site_url: "https://o9npuv8.github.io/mkdocs/"
site_dir: 'site'

site_name: Privacy Guides
site_description: |
  Massive organizations are monitoring your online activities. Privacy Guides is your central privacy and security resource to protect yourself online.
copyright: |
  <b>Privacy Guides</b> is a non-profit, socially motivated website that provides information for protecting your data security and privacy.<br>
  We do not make money from recommending certain products, and we do not utilize affiliate links.<br>
  This content was made available by the Privacy Guides team and contributors. <a href="https://github.com/privacyguides/privacyguides">Get involved</a>!

extra:
  generator: false
  analytics:
    provider: plausible
    property: privacyguides.org
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: hero/emoji-happy
          name: This page was helpful
          data: Helpful
          note: Thanks for your feedback!
        - icon: hero/emoji-sad
          name: This page could be improved
          data: Needs Improvement
          note: Thanks for your feedback! Help us improve this page by opening a <a href="https://github.com/orgs/privacyguides/discussions" target=_blank>discusson on GitHub</a>.
  social:
    - icon: pg/matrix
      link: https://matrix.to/#/#privacyguides:matrix.org
      name: Matrix
    - icon: fontawesome/brands/reddit-alien
      link: https://reddit.com/r/PrivacyGuides
      name: Reddit
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@privacyguides
      name: Mastodon
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/privacy_guides
      name: Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/privacyguides
      name: GitHub
repo_url: https://github.com/privacyguides/privacyguides.org
repo_name: ""
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: theme
  favicon: assets/brand/PNG/Favicon/favicon-32x32.png
  icon:
    repo: fontawesome/brands/github
  font: false
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - content.tooltips
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: deep purple
      toggle:
        icon: hero/sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: amber
      toggle:
        icon: hero/moon
        name: Switch to light mode
watch:
  - theme
  - includes

plugins:
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
  - i18n:
      default_language: en
      material_alternate: true
      languages:
        en:
          name: English
          build: false
  - tags
  - search
  - git-revision-date-localized:
      exclude:
        - index.en.md
  - rss:
      match_path: "blog/.*"
      pretty_print: true
      date_from_meta:
        as_creation: "created"
        datetime_format: "%Y-%m-%d"
  - privacy:
      externals_exclude:
        - cdn.jsdelivr.net/npm/mathjax@3/*
        - api.privacyguides.net/*
        - giscus.app/*
extra_css:
  - assets/stylesheets/extra.css?v=2.10.0
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - md_in_html
  - meta
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - theme/.icons
  - tables
  - footnotes
  - toc:
      permalink: true
      toc_depth: 4

extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/feedback.js

nav:
  - Home: 'index.md'
  - 'Knowledge Base':
    - 'The Basics':
      - 'basics/threat-modeling.md'
      - 'basics/common-threats.md'
      - 'basics/account-deletion.md'
      - 'basics/multi-factor-authentication.md'
      - 'basics/vpn-overview.md'
      - 'basics/tor-overview.md'
      - 'basics/dns-overview.md'
      - 'basics/email-security.md'
    - 'Android':
      - 'android/overview.md'
      - 'android/grapheneos-vs-calyxos.md'
    - 'Linux':
      - 'linux-desktop/overview.md'
      - 'linux-desktop/hardening.md'
      - 'linux-desktop/sandboxing.md'
    - 'Advanced':
      - 'advanced/integrating-metadata-removal.md'
      - 'advanced/erasing-data.md'
  - 'Recommendations':
    - 'tools.md'
    - 'Browsers':
      - 'browsers.md'
    - 'Operating Systems':
      - 'android.md'
      - 'linux-desktop.md'
      - 'qubes.md'
      - 'router.md'
    - 'Providers':
      - 'cloud.md'
      - 'dns.md'
      - 'email.md'
      - 'search-engines.md'
      - 'vpn.md'
    - 'Software':
      - 'calendar-contacts.md'
      - 'notebooks.md'
      - 'email-clients.md'
      - 'encryption.md'
      - 'file-sharing.md'
      - 'metadata-removal-tools.md'
      - 'multi-factor-authentication.md'
      - 'passwords.md'
      - 'productivity.md'
      - 'real-time-communication.md'
      - 'news-aggregators.md'
      - 'self-contained-networks.md'
      - 'video-streaming.md'
  - 'About':
    - 'about.md'
    - 'about/donate.md'
    - 'Online Services': 'https://privacyguides.net'
    - 'Website Statistics': 'https://stats.privacyguides.net/privacyguides.org'
    - 'about/notices.md'
    - 'about/privacy-policy.md'
  - 'Donate': '/about/donate/'
  - 'Discussions': 'https://github.com/orgs/privacyguides/discussions'
  - 'Blog':
    - '2022':
      - '"Move Fast and Break Things"': 'blog/2022/04/04/move-fast-and-break-things.md'
    - '2021':
      - 'Firefox Privacy: 2021 Update': 'blog/2021/12/01/firefox-privacy-2021-update.md'
      - 'Virtual Insanity': 'blog/2021/11/01/virtual-insanity.md'
      - 'Welcome to Privacy Guides': 'blog/2021/09/14/welcome-to-privacy-guides.md'
